name: Caller Wrokflow

on:
  push:
    branches:
      - dev
      - stage
      - prd
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # 手動実行を許可
jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
