name: Deploy CDK Stack

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:  # 手動実行を許可

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # PR時はデプロイをスキップし、ビルドのみ実行
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build all
        run: npm run build:all
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
            
      - name: CDK Deploy
        run: npx cdk deploy --require-approval never
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

  # PR時のビルドとテストのジョブ
  test:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build all
        run: npm run build:all
      
      - name: CDK Synth (validate CloudFormation)
        run: npx cdk synth
